config/routes.rb
Rails.application.routes.draw do
  get 'photos/home'
  get 'photos/about'
  get 'photos/contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  layout "photo"
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BootstrapThemes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/photo.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'photo', media: 'all'%>
    <%= yield :stylesheet %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'photo' %>
    <%= yield :javascript %>
  </body>
</html>

app/views/photos/_footer.html.erb
<footer>
  <div class="col-md-12">
    <a title="Source code for this website" target="_blank" href="https://github.com/jayzen/bootstrap-photo-app" class="btn btn-success">
      <i class="fa fa-code fa-lg"></i>
    </a>
    <a title="My GitHub" target="_blank" href="https://github.com/jayzen" class="btn btn-success">
      <i class="fa fa-github fa-lg"></i>
    </a>
  </div>
  <div class="col-md-12">
    <p>jayzen</p>
  </div>
</footer>

app/views/photos/_head.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Gamma", photos_home_path, class: "navbar-brand em-text" %>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                  <li class="<%= 'active' if action_name == 'home' %>"><%= link_to "home", photos_home_path %></li>
                  <li class="<%= 'active' if action_name == 'about' %>"><%= link_to "about", photos_about_path %></li>
                  <li class="<%= 'active' if action_name == 'contact' %>"><%= link_to "contact", photos_contact_path %></li>
                </ul>
            </div>
        </div>
</nav>

app/views/photos/about.html.erb
    <%= render 'photos/head'%>

    <section id="titlebar">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>About Gamma</h1>
                </div>
            </div>
        </div>
    </section>

    <section id="about">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <h2>Lorem Ipsum</h2>
                    <p>Donec at est sed nunc euismod tincidunt. Morbi vel tristique massa, ac luctus nulla. Cras aliquam velit bibendum magna condimentum, id mollis dolor aliquam. Vestibulum arcu justo, laoreet sit amet mi in, dignissim convallis erat. Sed tincidunt, nunc ut ultricies consequat</p>
                    <br/>
                    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingOne">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                      Collapsible Group Item #1
                                    </a>
                                  </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                <div class="panel-body">
                                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingTwo">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                      Collapsible Group Item #2
                                    </a>
                                  </h4>
                            </div>
                            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                                <div class="panel-body">
                                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingThree">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                      Collapsible Group Item #3
                                    </a>
                                  </h4>
                            </div>
                            <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                                <div class="panel-body">
                                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <%= image_tag "photos/demo2.jpg", class: "demo" %>
                    <h2>Lorem Ipsum</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam in ipsum mauris. Vestibulum tempus consectetur ipsum, vel euismod est dictum sed.</p>
                    <a href="#" class="btn btn-default">Read More</a>
                </div>
            </div>
        </div>
    </section>
    
    <%= render 'photos/footer' %>

app/views/photos/contact.html.erb
    <%= render 'photos/head' %>
    <section id="titlebar">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>Contact Us</h1>
                </div>
            </div>
        </div>
    </section>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <form>
                        <div class="form-group">
                            <label>Your Name</label>
                            <input type="text" class="form-control" placeholder="Your Name">
                        </div>
                        <div class="form-group">
                            <label>Company Name</label>
                            <input type="text" class="form-control" placeholder="Company Name">
                        </div>
                        <div class="form-group">
                            <label>Email address</label>
                            <input type="email" class="form-control" placeholder="Your Email">
                        </div>
                        <div class="form-group">
                            <label>Message</label>
                            <textarea class="form-control" placeholder="Wassup!!!"></textarea>
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                </div>
                <div class="col-md-4">
                  <%= image_tag "photos/demo2.jpg", class: "demo" %>
                    <h2>Lorem Ipsum</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam in ipsum mauris. Vestibulum tempus consectetur ipsum, vel euismod est dictum sed.</p>
                    <a href="#" class="btn btn-default">Read More</a>
                </div>
            </div>
        </div>
    </section>

    <%= render 'photos/footer' %>

app/views/photos/home.html.erb
    <%= render 'photos/head' %>
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                  <h1>Capture <span class="em-text">Life</span></h1>
                  <p>A fun and easy way to capture and share moment in your life</p>
                  <a href="#">
                    <%= image_tag "photos/icon_app_store.png", class: "app-btn" %>
                  </a>
                  <a href="#">
                    <%= image_tag "photos/icon_google_play.png", class: "app-bun" %>
                  </a>
                </div>
                <div class="col-md-6">
                  <%= image_tag "photos/site_phone.png", class: "showcase-img" %> 
                </div>
            </div>
        </div>
    </div>

    <section id="middle">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <%=image_tag "photos/demo1.jpg", class: "demo" %>
                    <h2>Lorem Ipsum</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam in ipsum mauris. Vestibulum tempus consectetur ipsum, vel euismod est dictum sed.</p>
                    <a href="#" class="btn btn-default">Read More</a>
                </div>
                <div class="col-md-4">
                    <%=image_tag "photos/demo2.jpg", class: "demo" %>
                    <h2>Lorem Ipsum</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam in ipsum mauris. Vestibulum tempus consectetur ipsum, vel euismod est dictum sed.</p>
                    <a href="#" class="btn btn-default">Read More</a>
                </div>
                <div class="col-md-4">
                    <%=image_tag "photos/demo3.jpg", class: "demo" %>
                    <h2>Lorem Ipsum</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam in ipsum mauris. Vestibulum tempus consectetur ipsum, vel euismod est dictum sed.</p>
                    <a href="#" class="btn btn-default">Read More</a>
                </div>
            </div>
        </div>
    </section>

    <section id="feature">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <h1>Gamma Features</h1>
                    <ul>
                        <li><i class="glyphicon glyphicon-ok">&nbsp;</i>Maecenas porttitor e</li>
                        <li><i class="glyphicon glyphicon-ok">&nbsp;</i>ies bland</li>
                        <li><i class="glyphicon glyphicon-ok">&nbsp;</i>et justo, ut ult</li>
                        <li><i class="glyphicon glyphicon-ok">&nbsp;</i>Sed eu lorem ac </li>
                        <li><i class="glyphicon glyphicon-ok">&nbsp;</i>Donec eget moll</li>
                    </ul>
                </div>
                <div class="col-md-4 col-md-offset-2">
                  <%= image_tag "photos/logo.png", class: "big-logo" %>
                </div>
            </div>
        </div>
    </section>

    <%= render 'photos/footer'%>